#ifndef MQTT_CREDENTIALS_H
#define MQTT_CREDENTIALS_H


/*
  DEFINE - MQTT CREDENTIALS
*/
#define MQTT_HOST "MQTT_BROKER_HERE"
#define MQTT_PORT MQTT_PORT_HERE
#define MQTT_USER "MQTT_USER_HERE"
#define MQTT_PASSWORD "MQTT_PASSWORD_HERE"
#define MQTT_SECRET_HASH "MQTT_SECRET_HASH_HERE"
#define MQTT_PUBLIC_HASH "MQTT_PUBLIC_HASH_HERE"


#endif